data:
  type: 'rt-polarity'
  base_path: 'data/'
  raw_data_path: 'rt-polaritydata/'
  processed_path: 'rt-polarity_processed_data'
  testset_size: 2000
  num_classes: 2
  PAD_ID: 0

model:
  batch_size: 64
  embed_type: 'rand'     #(rand, static, non-static, multichannel)
  pretrained_embed: ""
  embed_dim: 300
  num_filters: 256
  filter_sizes:
    - 2
    - 3
    - 4
    - 5
  dropout: 0.5

train:
  learning_rate: 0.00001

  train_steps: 20000
  model_dir: 'logs/rt-polarity'

  save_checkpoints_steps: 100
  loss_hook_n_iter: 100
  check_hook_n_iter: 100
  min_eval_frequency: 100

  print_verbose: True
  debug: False

slack:
  webhook_url: ""
